[eye]
paths = [
  "eye/*"
]
channels = ["stable"]

[mfold]
paths = [
  "mfold/*"
]
channels = ["stable"]

[viennarna]
paths = [
  "viennarna/*"
]
channels = ["stable"]

[elixir]
paths = [
  "elixir/*"
]
channels = ["stable"]

